# Generated by Django 5.2.14 on 2026-05-22 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("role", models.CharField(max_length=120)),
                ("company", models.CharField(max_length=120)),
                ("location", models.CharField(blank=True, max_length=120)),
                ("start_year", models.PositiveIntegerField()),
                (
                    "end_year",
                    models.PositiveIntegerField(
                        blank=True, help_text="Leave empty for “Present”", null=True
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "highlights",
                    models.TextField(blank=True, help_text="One highlight per line"),
                ),
                (
                    "stack",
                    models.CharField(
                        blank=True, help_text="Comma-separated", max_length=300
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Experience",
                "ordering": ["order", "-start_year"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=120)),
                ("slug", models.SlugField(blank=True, max_length=140, unique=True)),
                ("year", models.PositiveIntegerField()),
                (
                    "short_description",
                    models.TextField(help_text="120–180 chars · used in cards"),
                ),
                ("role", models.CharField(blank=True, max_length=120)),
                ("client", models.CharField(blank=True, max_length=120)),
                ("live_url", models.URLField(blank=True)),
                ("repo_url", models.URLField(blank=True)),
                (
                    "tech_stack",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated, e.g. Django, Postgres, HTMX",
                        max_length=300,
                    ),
                ),
                ("cover_image_url", models.URLField(blank=True)),
                (
                    "card_style",
                    models.CharField(
                        choices=[
                            ("mosaic", "Mosaic"),
                            ("ledger", "Ledger"),
                            ("roost", "Roost"),
                            ("drift", "Drift"),
                            ("quill", "Quill"),
                            ("atlas", "Atlas"),
                        ],
                        default="mosaic",
                        help_text="Gradient style for the card background",
                        max_length=20,
                    ),
                ),
                ("case_study_body", models.TextField(blank=True, help_text="Markdown")),
                ("meta_title", models.CharField(blank=True, max_length=180)),
                ("meta_description", models.CharField(blank=True, max_length=300)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "badge",
                    models.CharField(
                        choices=[
                            ("live", "En production"),
                            ("beta", "En bêta"),
                            ("working", "En cours"),
                            ("oss", "Open source"),
                            ("archived", "Archivé"),
                        ],
                        default="working",
                        max_length=20,
                    ),
                ),
                ("featured", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "-year", "title"],
            },
        ),
        migrations.CreateModel(
            name="SiteProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(default="Rukundo Ronaldo", max_length=120)),
                ("tagline", models.CharField(blank=True, max_length=200)),
                ("bio", models.TextField(blank=True)),
                ("location", models.CharField(blank=True, max_length=120)),
                ("timezone", models.CharField(blank=True, max_length=60)),
                ("availability", models.CharField(blank=True, max_length=120)),
                ("hero_prefix", models.CharField(blank=True, max_length=120)),
                ("hero_heading", models.TextField(blank=True)),
                ("hero_sub", models.TextField(blank=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("github_url", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                ("twitter_url", models.URLField(blank=True)),
                ("dribbble_url", models.URLField(blank=True)),
                (
                    "accent_color",
                    models.CharField(default="#c084fc", help_text="Hex", max_length=9),
                ),
                ("resume_url", models.URLField(blank=True)),
            ],
            options={
                "verbose_name": "Site profile",
                "verbose_name_plural": "Site profile",
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=80)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("backend", "Backend"),
                            ("frontend", "Frontend"),
                            ("tooling", "Tooling & infra"),
                        ],
                        default="backend",
                        max_length=20,
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("primary", "Au quotidien"),
                            ("frequent", "Fréquent"),
                            ("occasional", "Occasionnel"),
                        ],
                        default="frequent",
                        max_length=20,
                    ),
                ),
                ("favorite", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["category", "order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quote", models.TextField()),
                ("author", models.CharField(max_length=120)),
                (
                    "author_role",
                    models.CharField(
                        blank=True, help_text="Role · company", max_length=160
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
