# Generated by Django 5.2.14 on 2026-05-22 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0004_seed_extra"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteprofile",
            name="photo_url",
            field=models.URLField(
                blank=True, help_text="Portrait shown in the À propos section"
            ),
        ),
        migrations.AlterField(
            model_name="siteprofile",
            name="bio",
            field=models.TextField(blank=True, help_text="One paragraph per line"),
        ),
    ]
