# Generated by Django 5.2.14 on 2026-06-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0006_seed_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteprofile",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Portrait shown in the À propos section (uploaded file). Takes priority over Photo URL.",
                upload_to="profile/",
            ),
        ),
        migrations.AlterField(
            model_name="siteprofile",
            name="photo_url",
            field=models.URLField(
                blank=True,
                help_text="Fallback portrait URL, used only if no file is uploaded above",
            ),
        ),
    ]
