# Generated by Django 5.2.14 on 2026-06-23 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0008_clear_seeded_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "degree",
                    models.CharField(
                        help_text="e.g. Bachelor — Développement Web", max_length=160
                    ),
                ),
                ("school", models.CharField(max_length=120)),
                (
                    "field",
                    models.CharField(
                        blank=True,
                        help_text="Sub-line, e.g. “Titre RNCP niveau 7 (Bac+5)”",
                        max_length=160,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=120)),
                ("start_year", models.PositiveIntegerField()),
                (
                    "end_year",
                    models.PositiveIntegerField(
                        blank=True, help_text="Leave empty for “Present”", null=True
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Education",
                "verbose_name_plural": "Education",
                "ordering": ["order", "-start_year"],
            },
        ),
    ]
