# Generated by Django 5.2.14 on 2026-06-26 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0012_student_bio"),
    ]

    operations = [
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(blank=True, upload_to="gallery/")),
                (
                    "image_url",
                    models.URLField(
                        blank=True, help_text="Fallback if no file uploaded"
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=160)),
                (
                    "taken",
                    models.CharField(
                        blank=True, help_text="e.g. “Lyon · 2025”", max_length=24
                    ),
                ),
                (
                    "span",
                    models.CharField(
                        blank=True,
                        help_text="Mosaic span: '', 'cw' (col-wide), 'rh' (row-tall), 'cwrh' (both)",
                        max_length=8,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "key",
                    models.SlugField(
                        help_text="Stable id, e.g. about, stack, work, log, edu, ai, gallery, contact",
                        unique=True,
                    ),
                ),
                ("nav_label", models.CharField(max_length=24)),
                (
                    "number",
                    models.PositiveIntegerField(
                        help_text="Shown as the eyebrow index, e.g. 01"
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=120)),
                (
                    "accent",
                    models.CharField(
                        choices=[
                            ("violet", "Violet"),
                            ("cyan", "Cyan"),
                            ("lime", "Lime"),
                            ("pink", "Pink"),
                        ],
                        default="violet",
                        max_length=8,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="education",
            name="accent",
            field=models.CharField(
                choices=[
                    ("violet", "Violet"),
                    ("cyan", "Cyan"),
                    ("lime", "Lime"),
                    ("pink", "Pink"),
                ],
                default="cyan",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="education",
            name="is_target",
            field=models.BooleanField(
                default=False, help_text="Highlight as the formation being targeted"
            ),
        ),
        migrations.AddField(
            model_name="education",
            name="rncp_level",
            field=models.CharField(
                blank=True,
                help_text="e.g. “RNCP 7” — shown as a clearance level",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="education",
            name="status_label",
            field=models.CharField(
                blank=True, help_text="e.g. “En cours”, “Visé 2026”", max_length=40
            ),
        ),
        migrations.AddField(
            model_name="experience",
            name="accent",
            field=models.CharField(
                choices=[
                    ("violet", "Violet"),
                    ("cyan", "Cyan"),
                    ("lime", "Lime"),
                    ("pink", "Pink"),
                ],
                default="violet",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="accent",
            field=models.CharField(
                choices=[
                    ("violet", "Violet"),
                    ("cyan", "Cyan"),
                    ("lime", "Lime"),
                    ("pink", "Pink"),
                ],
                default="violet",
                help_text="Neon accent used by the v2 design",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="category",
            field=models.CharField(
                blank=True,
                help_text="v2 card category, e.g. “Full-stack · SaaS”",
                max_length=80,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="highlights",
            field=models.TextField(
                blank=True, help_text="v2 case-study highlights, one per line"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="lead",
            field=models.CharField(
                blank=True,
                help_text="v2 punchy one-liner; falls back to short_description",
                max_length=240,
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="lat",
            field=models.CharField(blank=True, default="45.7640", max_length=16),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="logo_super",
            field=models.CharField(default="2", max_length=4),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="logo_text",
            field=models.CharField(default="R", max_length=8),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="lon",
            field=models.CharField(blank=True, default="4.8357", max_length=16),
        ),
        migrations.CreateModel(
            name="ProjectShot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(blank=True, upload_to="projects/shots/")),
                (
                    "image_url",
                    models.URLField(
                        blank=True, help_text="Fallback if no file uploaded"
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=160)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shots",
                        to="pages.project",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]
