# Generated by Django 5.2.14 on 2026-06-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0015_reseed_sections_v2"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteprofile",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Display format, e.g. 06 16 20 34 95",
                max_length=32,
            ),
        ),
    ]
