# Generated by Django 5.2.14 on 2026-06-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0017_cv_resume_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteprofile",
            name="resume_url",
            field=models.CharField(
                blank=True,
                help_text="Site-relative path (e.g. /cv/Rukundo-Ronaldo-CV.pdf) or a full URL.",
                max_length=300,
            ),
        ),
    ]
