# Generated by Django 5.2.14 on 2026-08-20 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0018_alter_siteprofile_resume_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                (
                    "body",
                    models.TextField(
                        blank=True,
                        help_text="Markdown: ## headings, - bullets, **bold**, `code`",
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, upload_to="projects/sections/"),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True, help_text="Fallback if no file uploaded"
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True,
                        help_text="Shown under the screenshot",
                        max_length=160,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="pages.project",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]
