# Generated by Django 5.2.14 on 2026-08-20 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0019_projectsection"),
    ]

    operations = [
        migrations.CreateModel(
            name="SectionMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, upload_to="projects/sections/"),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True, help_text="Fallback if no image file uploaded"
                    ),
                ),
                (
                    "document",
                    models.FileField(
                        blank=True,
                        help_text="PDF or any file offered for download (takes precedence over the image)",
                        upload_to="projects/documents/",
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=160)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="pages.projectsection",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "section media",
                "ordering": ["order", "id"],
            },
        ),
    ]
