# Generated by Django 5.2.14 on 2026-05-22 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_seed_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(blank=True, max_length=160)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="project",
            name="open_source",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="show_in_index",
            field=models.BooleanField(default=True, help_text="Show in the work index"),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="default_theme",
            field=models.CharField(
                choices=[("dark", "Dark"), ("light", "Light"), ("system", "System")],
                default="dark",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="home_variant",
            field=models.CharField(
                choices=[
                    ("atelier", "Atelier · editorial"),
                    ("etudes", "Études · grid"),
                ],
                default="atelier",
                help_text="Which home layout to serve at /",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="featured",
            field=models.BooleanField(default=False, help_text="Featured on home"),
        ),
        migrations.CreateModel(
            name="ProjectMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=80)),
                ("value", models.CharField(max_length=40)),
                (
                    "unit",
                    models.CharField(
                        blank=True, help_text="Suffix, e.g. ms, teams", max_length=40
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="pages.project",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]
