"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.0.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path

from django.templatetags.static import static
from django.urls import reverse_lazy

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Dev fallback only — set DJANGO_SECRET_KEY in production.
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-)$df%j4@#j2t-v!^%=(6y6p8ujidwi!js+%8e_o5$78q)1#wxd",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "True") == "True"

ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")


# Application definition

INSTALLED_APPS = [
    # Unfold must precede django.contrib.admin to override the admin templates.
    "unfold",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "pages",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        # Lives under data/ so a Docker volume can persist it (see docker-compose.yml).
        "NAME": BASE_DIR / "data" / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "fr"

TIME_ZONE = "Europe/Paris"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

# WhiteNoise: compressed, hashed static files served by the app itself.
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Unfold admin theme — brand-matched to the editorial admin design
# (reference/admin.html): purple accent, warm near-black dark palette,
# Instrument Serif / Geist / Geist Mono fonts via static/css/admin.css.
# https://unfoldadmin.com/docs/configuration/
UNFOLD = {
    "SITE_TITLE": "Rukundo Ronaldo — Admin",
    "SITE_HEADER": "Rukundo Ronaldo",
    "SITE_SUBHEADER": "Portfolio",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "STYLES": [lambda request: static("css/admin.css")],
    "DASHBOARD_CALLBACK": "pages.dashboard.dashboard_callback",
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "Content",
                "separator": False,
                "items": [
                    {"title": "Dashboard", "icon": "dashboard",
                     "link": reverse_lazy("admin:index")},
                    {"title": "Projects", "icon": "deployed_code",
                     "link": reverse_lazy("admin:pages_project_changelist"),
                     "badge": "pages.dashboard.project_count"},
                    {"title": "Experience", "icon": "timeline",
                     "link": reverse_lazy("admin:pages_experience_changelist"),
                     "badge": "pages.dashboard.experience_count"},
                    {"title": "Skills", "icon": "bolt",
                     "link": reverse_lazy("admin:pages_skill_changelist"),
                     "badge": "pages.dashboard.skill_count"},
                    {"title": "Testimonials", "icon": "format_quote",
                     "link": reverse_lazy("admin:pages_testimonial_changelist"),
                     "badge": "pages.dashboard.testimonial_count"},
                    {"title": "Messages", "icon": "inbox",
                     "link": reverse_lazy("admin:pages_contactmessage_changelist"),
                     "badge": "pages.dashboard.message_count"},
                ],
            },
            {
                "title": "Site",
                "separator": True,
                "items": [
                    {"title": "Profile", "icon": "person",
                     "link": reverse_lazy("admin:pages_siteprofile_changelist")},
                    {"title": "Hero copy", "icon": "article",
                     "link": reverse_lazy("admin:pages_siteprofile_changelist")},
                    {"title": "Contact & socials", "icon": "alternate_email",
                     "link": reverse_lazy("admin:pages_siteprofile_changelist")},
                    {"title": "Theme & branding", "icon": "palette",
                     "link": reverse_lazy("admin:pages_siteprofile_changelist")},
                    {"title": "Resume / CV", "icon": "description",
                     "link": reverse_lazy("admin:pages_siteprofile_changelist")},
                ],
            },
            {
                "title": "System",
                "separator": True,
                "items": [
                    {"title": "Users", "icon": "group",
                     "link": reverse_lazy("admin:auth_user_changelist")},
                    {"title": "Activity Log", "icon": "history",
                     "link": reverse_lazy("admin:admin_logentry_changelist")},
                ],
            },
        ],
    },
    "COLORS": {
        # Accent — Tailwind "purple" ramp (purple-400 = #c084fc, the brand accent).
        "primary": {
            "50": "250 245 255",
            "100": "243 232 255",
            "200": "233 213 255",
            "300": "216 180 254",
            "400": "192 132 252",
            "500": "168 85 247",
            "600": "147 51 234",
            "700": "126 34 206",
            "800": "107 33 168",
            "900": "88 28 135",
            "950": "59 7 100",
        },
        # Base — warm near-black grays from shared.css (--bg / --ink family),
        # so dark mode reads as the editorial #0e0d0c rather than cold gray.
        "base": {
            "50": "245 242 236",
            "100": "235 231 223",
            "200": "214 210 200",
            "300": "176 170 160",
            "400": "138 131 120",
            "500": "109 103 96",
            "600": "74 70 65",
            "700": "42 39 34",
            "800": "29 28 26",
            "900": "22 21 19",
            "950": "14 13 12",
        },
    },
}


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
